- name: "Git Pull"
  hosts: all
  tasks:
  - shell:
      cmd: git -c http.proxy= pull origin master
      chdir: /home/devopsteam/ansible_test/threatlandscape
      args:
        executable: /usr/bin/git
